# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5047d9f7641b775206c02daa6b5faaf8cb0848c57d30865bc0e57ca9a70310e2e4929b0f4dc3357982660efdd33c335c9ed4845d23cecd7b7680687c30fcce64

test:
  secret_key_base: c6eecfbb7be251e46e9db4dcc026026d4321f3be891ad40f0cfb90d244e8e9a082226fb67e61efb550b2351b8b60cd4832cf698a8169b4e421cb9144735a3cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
